services:
  django:
    build: .
    container_name: lyricsnest
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"

volumes:
  static_volume:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /home/nicoferr/lyricsnest/staticfiles
    #   o: bind