# Generated by Django 5.2.4 on 2025-07-31 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lyrics', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 7, 31, 12, 58, 39, 420519, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
